name: Development
run-name: ${{ github.actor }} is compiling our Sample App 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile Job
    permissions: write-all
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}/Sports
    steps:
      - uses: actions/checkout@v3
      - name: Pull Dev PASOE Docker Image
        run: |
          docker login ${{ vars.DOCKER_REPO_URL }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
          docker pull ${{ vars.DOCKER_REPO_URL }}/openedge-dev-pasoe:${{ vars.OE_VERSION }}
      - name: Running Gradle build in a Container
        run: docker run --rm -v ./:/psc/wrk/Sports/ -e APP_LOCATION=/psc/wrk/Sports ${{ vars.DOCKER_REPO_URL }}/openedge-dev-pasoe:${{ vars.OE_VERSION }}
      - name: Setup Python - needed by publish step
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Publish ABL Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: ${{ github.workspace }}/Sports/build/test-results/test/*.xml
          check_name: Test Results - ABL Unit tests for Sports App